package com.springtour.stockservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.1
 * Tue Aug 27 14:21:31 CST 2013
 * Generated source version: 2.3.1
 * 
 */
 
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "ChinaStockWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ChinaStockWebServiceSoap {

    @WebResult(name = "getStockImageByteByCodeResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getStockImageByteByCode", targetNamespace = "http://WebXml.com.cn/", className = "com.springtour.stockservice.GetStockImageByteByCode")
    @WebMethod(action = "http://WebXml.com.cn/getStockImageByteByCode")
    @ResponseWrapper(localName = "getStockImageByteByCodeResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.springtour.stockservice.GetStockImageByteByCodeResponse")
    public byte[] getStockImageByteByCode(
        @WebParam(name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theStockCode
    );

    @WebResult(name = "getStockInfoByCodeResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getStockInfoByCode", targetNamespace = "http://WebXml.com.cn/", className = "com.springtour.stockservice.GetStockInfoByCode")
    @WebMethod(action = "http://WebXml.com.cn/getStockInfoByCode")
    @ResponseWrapper(localName = "getStockInfoByCodeResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.springtour.stockservice.GetStockInfoByCodeResponse")
    public com.springtour.stockservice.ArrayOfString getStockInfoByCode(
        @WebParam(name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theStockCode
    );

    @WebResult(name = "getStockImage_kByteByCodeResult", targetNamespace = "http://WebXml.com.cn/")
    @RequestWrapper(localName = "getStockImage_kByteByCode", targetNamespace = "http://WebXml.com.cn/", className = "com.springtour.stockservice.GetStockImageKByteByCode")
    @WebMethod(operationName = "getStockImage_kByteByCode", action = "http://WebXml.com.cn/getStockImage_kByteByCode")
    @ResponseWrapper(localName = "getStockImage_kByteByCodeResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.springtour.stockservice.GetStockImageKByteByCodeResponse")
    public byte[] getStockImageKByteByCode(
        @WebParam(name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theStockCode,
        @WebParam(name = "theType", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theType
    );

    @RequestWrapper(localName = "getStockImage_kByCode", targetNamespace = "http://WebXml.com.cn/", className = "com.springtour.stockservice.GetStockImageKByCode")
    @WebMethod(operationName = "getStockImage_kByCode", action = "http://WebXml.com.cn/getStockImage_kByCode")
    @ResponseWrapper(localName = "getStockImage_kByCodeResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.springtour.stockservice.GetStockImageKByCodeResponse")
    public void getStockImageKByCode(
        @WebParam(name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theStockCode,
        @WebParam(name = "theType", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theType
    );

    @RequestWrapper(localName = "getStockImageByCode", targetNamespace = "http://WebXml.com.cn/", className = "com.springtour.stockservice.GetStockImageByCode")
    @WebMethod(action = "http://WebXml.com.cn/getStockImageByCode")
    @ResponseWrapper(localName = "getStockImageByCodeResponse", targetNamespace = "http://WebXml.com.cn/", className = "com.springtour.stockservice.GetStockImageByCodeResponse")
    public void getStockImageByCode(
        @WebParam(name = "theStockCode", targetNamespace = "http://WebXml.com.cn/")
        java.lang.String theStockCode
    );
}
